### PR TITLE
Some fixes for first release

### LINKED ISSUE #10: Checklist for registering / v0.1.0
Just putting small stuff here so we wouldn't forget.

- [ ] Update installation instructions in the README.
- [ ] Fix #14
- [ ] Add REQUIRE since it is needed for registering in Metadata
- [ ] Update the uuid to be metadata compatible.

### LINKED ISSUE #14: generate() should set up HTML output by default
Ref: https://github.com/JuliaDocs/Documenter.jl/pull/826#pullrequestreview-153579663

### PR DESCRIPTION
**Pull request by fredrikekre**
fix #14, fix #10

### CODE REVIEW

File: src/Generator.jl [hunk 1]
```diff
@@ -62,11 +65,20 @@ $(SIGNATURES)
...
-    """
-    [deps]
-    Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
-    """
+function project(;format = :html)
+    deps = Dict("Documenter" => "e30172f5-a6a5-5a46-863b-614d45cd2de4")
+    if format === :markdown
+        deps["DocumenterMarkdown"] = "997ab1e6-3595-5248-9280-8efb232c3433"
+    elseif format === :pdf
+        deps["DocumenterLatex"] = "3788732c-1b3f-57a6-b166-8dda46668e9b"
```
Comment (fredrikekre) [inline src/Generator.jl]: This should be `DocumenterLaTeX`

**Comment by fredrikekre** [comment]
Looks like I need to update the tests too.
